import logging
from typing import Optional

from langchain_aws import ChatBedrockConverse
from langchain_core.messages import HumanMessage
from github import Github, GithubException

from app.core.config import settings
from app.integrations.github.auth import github_auth

logger = logging.getLogger(__name__)

FIX_GENERATION_PROMPT = """You are an expert SRE writing a code fix for a Kubernetes application issue.

## Incident Context
{incident_summary}

## Root Cause
{root_cause}

## Suggested Remediation
{remediation_action}

## File to Modify
Path: {file_path}

Current content:
```{file_extension}
{current_content}
```

## Your Task
Generate a code fix that implements the remediation. Return ONLY the modified file content (full file, not a diff).

Requirements:
- Preserve all existing code except what needs to change
- Add comments explaining the fix
- Follow existing code style and formatting
- Make minimal changes (only what's needed to fix the issue)

Output the complete modified file:
```{file_extension}
<your modified file here>
```
"""


class FixPRGenerator:

    def __init__(self):
        self.github_auth = github_auth
        self.model = ChatBedrockConverse(
            model=settings.BEDROCK_MODEL_ID,
            region_name=settings.AWS_REGION,
            temperature=0,
            max_tokens=4096,
        )

    async def create_fix_pr(
        self,
        investigation_id: str,
        owner: str,
        repo: str,
        file_path: str,
        incident_summary: str,
        root_cause: str,
        remediation_action: str,
        risk_level: str = "medium",
        base_branch: str = "main",
    ) -> Optional[str]:
        if not self.github_auth:
            logger.error("GitHub auth not configured")
            return None

        try:
            installation_id = await self.github_auth.get_installation_id_for_repo(owner, repo)
            if not installation_id:
                logger.error(f"No GitHub installation for {owner}/{repo}")
                return None

            client = await self.github_auth.get_client_for_installation(installation_id)
            gh_repo = client.get_repo(f"{owner}/{repo}")

            try:
                file_content_obj = gh_repo.get_contents(file_path, ref=base_branch)
                current_content = file_content_obj.decoded_content.decode("utf-8")
            except Exception as e:
                logger.error(f"Failed to fetch file {file_path}: {e}")
                return None

            file_extension = file_path.split(".")[-1]
            fixed_content = await self._generate_fix(
                incident_summary=incident_summary,
                root_cause=root_cause,
                remediation_action=remediation_action,
                file_path=file_path,
                file_extension=file_extension,
                current_content=current_content,
            )

            if not fixed_content:
                logger.error("Failed to generate fix")
                return None

            branch_name = f"sentryops/fix-{investigation_id[:8]}"
            base_ref = gh_repo.get_git_ref(f"heads/{base_branch}")
            try:
                gh_repo.create_git_ref(
                    ref=f"refs/heads/{branch_name}",
                    sha=base_ref.object.sha,
                )
                logger.info(f"Created branch: {branch_name}")
            except GithubException as e:
                if e.status == 422:
                    logger.info(f"Branch {branch_name} already exists")
                else:
                    raise

            commit_message = (
                f"fix: {remediation_action}\n\n"
                f"Generated by SentryOps Guardian\n"
                f"Investigation: {investigation_id}"
            )

            gh_repo.update_file(
                path=file_path,
                message=commit_message,
                content=fixed_content,
                sha=file_content_obj.sha,
                branch=branch_name,
            )

            pr_title = f"[SentryOps] Fix: {remediation_action[:60]}"
            pr_body = self._build_pr_description(
                investigation_id=investigation_id,
                incident_summary=incident_summary,
                root_cause=root_cause,
                remediation_action=remediation_action,
                risk_level=risk_level,
                file_path=file_path,
            )

            pr = gh_repo.create_pull(
                title=pr_title,
                body=pr_body,
                head=branch_name,
                base=base_branch,
            )

            logger.info(f"Created PR: {pr.html_url}")
            return pr.html_url

        except GithubException as e:
            logger.error(f"GitHub API error: {e}")
            return None
        except Exception as e:
            logger.error(f"Failed to create fix PR: {e}")
            return None

    async def _generate_fix(
        self,
        incident_summary: str,
        root_cause: str,
        remediation_action: str,
        file_path: str,
        file_extension: str,
        current_content: str,
    ) -> Optional[str]:
        prompt = FIX_GENERATION_PROMPT.format(
            incident_summary=incident_summary,
            root_cause=root_cause,
            remediation_action=remediation_action,
            file_path=file_path,
            file_extension=file_extension,
            current_content=current_content,
        )

        try:
            response = await self.model.ainvoke([HumanMessage(content=prompt)])
            response_text = response.content if isinstance(response.content, str) else str(response.content)

            if f"```{file_extension}" in response_text:
                code = response_text.split(f"```{file_extension}")[1].split("```")[0].strip()
            elif "```" in response_text:
                code = response_text.split("```")[1].split("```")[0].strip()
            else:
                code = response_text.strip()

            return code

        except Exception as e:
            logger.error(f"Failed to generate fix with Claude: {e}")
            return None

    def _build_pr_description(
        self,
        investigation_id: str,
        incident_summary: str,
        root_cause: str,
        remediation_action: str,
        risk_level: str,
        file_path: str,
    ) -> str:
        risk_emoji = {"low": "🟢", "medium": "🟡", "high": "🔴"}.get(risk_level, "⚪")

        return (
            f"## 🤖 SentryOps Guardian Auto-Fix\n\n"
            f"This PR was automatically generated by SentryOps Guardian in response to an incident.\n\n"
            f"### Incident Summary\n{incident_summary}\n\n"
            f"### Root Cause\n{root_cause}\n\n"
            f"### Remediation\n{remediation_action}\n\n"
            f"### Risk Level\n{risk_emoji} **{risk_level.upper()}**\n\n"
            f"### Files Changed\n- `{file_path}`\n\n"
            f"### Investigation\n"
            f"View full investigation: [Investigation {investigation_id}]"
            f"({settings.FRONTEND_URL}/investigations/{investigation_id})\n\n"
            f"### Testing\n"
            f"- [ ] Review the code changes\n"
            f"- [ ] Test in a staging environment\n"
            f"- [ ] Monitor metrics after deployment\n\n"
            f"---\n\n"
            f"**Guardian Confidence**: This fix was generated with AI assistance. "
            f"Please review carefully before merging.\n"
        )


fix_pr_generator = FixPRGenerator()
