"use client"

import { useState, useEffect } from "react"
import { Sparkles } from "lucide-react"
import { SuggestionCard } from "./suggestion-card"
import { getAlertSuggestions, acceptSuggestion, dismissSuggestion } from "@/lib/api/alerts"
import type { AlertSuggestion } from "@/lib/types/api"

export function SuggestionsSection() {
  const [suggestions, setSuggestions] = useState<AlertSuggestion[]>([])
  const [loadingIds, setLoadingIds] = useState<Set<string>>(new Set())

  useEffect(() => {
    getAlertSuggestions()
      .then((res) => setSuggestions(res.suggestions))
      .catch(() => {})
  }, [])

  if (suggestions.length === 0) return null

  async function handleAccept(id: string) {
    setLoadingIds((prev) => new Set(prev).add(id))
    try {
      await acceptSuggestion(id)
      setSuggestions((prev) => prev.filter((s) => s.id !== id))
    } finally {
      setLoadingIds((prev) => {
        const next = new Set(prev)
        next.delete(id)
        return next
      })
    }
  }

  async function handleDismiss(id: string) {
    setLoadingIds((prev) => new Set(prev).add(id))
    try {
      await dismissSuggestion(id)
      setSuggestions((prev) => prev.filter((s) => s.id !== id))
    } finally {
      setLoadingIds((prev) => {
        const next = new Set(prev)
        next.delete(id)
        return next
      })
    }
  }

  return (
    <div className="animate-in fade-in duration-500 space-y-3">
      <div className="flex items-center gap-2">
        <Sparkles className="h-4 w-4 text-violet-400" />
        <h2 className="text-sm font-semibold text-foreground">AI Suggestions</h2>
        <span className="rounded-full bg-violet-500/20 text-violet-400 px-2 py-0.5 text-[10px] font-semibold">
          {suggestions.length}
        </span>
        <span className="text-xs text-muted-foreground">
          · Generated by Guardian investigation
        </span>
      </div>
      <div className="space-y-3">
        {suggestions.map((s) => (
          <SuggestionCard
            key={s.id}
            suggestion={s}
            onAccept={() => handleAccept(s.id)}
            onDismiss={() => handleDismiss(s.id)}
            actionLoading={loadingIds.has(s.id)}
          />
        ))}
      </div>
    </div>
  )
}
